
# This file is automatically generated, you probably don't want to edit this

webrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "webrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="WebRConnect",
                name="webr",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

webrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "webrResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Web R")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Web R",
                visible=TRUE))}))

webrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "webrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "WebRConnect",
                name = "webr",
                version = c(1,0,0),
                options = options,
                results = webrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Web R
#'
#' 
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
webr <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("webr requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- webrOptions$new()

    analysis <- webrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

